### PR TITLE
Prevent i915kms link error

### PR DESCRIPTION
**Pull request by cperciva**
The functions intel_overlay_print_error_state, intel_display_print_error_state, and i915_error_state_free are only defined if CONFIG_DEBUG_FS is defined.  Maybe part or all of i915_debug.c should also be compiled only in that case; I don't know the code well enough to comment.  Taking out the calls to those functions makes it possible for the i915kms kernel module to load, however.

### CODE REVIEW

**Comment by kwm81** [comment]
Shouldn't this be restored to the "original"?

#if defined(CONFIG_DEBUG_FS)

**Comment by dumbbell** [comment]
I'm uncommentting the code guarded by `CONFIG_DEBUG_FS`. This code is enabled in HEAD already, I don't want to disable it.

**Comment by cperciva** [comment]
That also works!  I wasn't sure if the CONFIG_DEBUG_FS bits needed some special linuxy magic.

**Comment by dumbbell** [comment]
Not really, it mostly construct a large string which becomes the content of a file in Linux' sysfs or a sysctl on FreeBSD.

**Pull request closed without merging**
